/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    uploads: Upload;
    projects: Project;
  };
  globals: {
    'global-info': GlobalInfo;
    homepage: Homepage;
    'contact-page': ContactPage;
  };
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Upload {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Project {
  id: string;
  name: string;
  services: string;
  year: number;
  projectType: 'website' | 'ecommerce' | 'webApp';
  liveUrl?: string;
}
export interface GlobalInfo {
  id: string;
  maintenance: boolean;
  footerContactMethods: {
    name: string;
    url: string;
    id?: string;
  }[];
}
export interface Homepage {
  id: string;
  hero: {
    gallery: {
      img: string | Upload;
      id?: string;
    }[];
  };
  about: {
    title: string;
    subtext: string;
  };
  featProjects: {
    projects: string[] | Project[];
  };
  bottomMarquee: {
    gallery: {
      img: string | Upload;
      id?: string;
    }[];
  };
}
export interface ContactPage {
  id: string;
  avatar: string | Upload;
  contactMethods: {
    name: string;
    url: string;
    id?: string;
  }[];
  info: {
    name: string;
    id?: string;
  }[];
  otherMedia: {
    name: string;
    url: string;
    id?: string;
  }[];
}
